apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-04-21T17:37:10Z"
  generation: 1
  labels:
    kind: echo
    name: echo-same-node
  name: echo-same-node
  namespace: cilium-test
  resourceVersion: "3439"
  uid: 3abde799-9540-491a-86d8-a3094614e9b6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      kind: echo
      name: echo-same-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        kind: echo
        name: echo-same-node
        other: echo
      name: echo-same-node
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - client
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: NAMED_PORT
          value: http-8080
        image: quay.io/cilium/json-mock:v1.3.3@sha256:f26044a2b8085fcaa8146b6b8bb73556134d7ec3d5782c6a04a058c945924ca0
        imagePullPolicy: IfNotPresent
        name: echo-same-node
        ports:
        - containerPort: 8080
          hostPort: 40000
          name: http-8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - -conf
        - /etc/coredns/Corefile
        image: docker.io/coredns/coredns:1.10.0@sha256:017727efcfeb7d053af68e51436ce8e65edbc6ca573720afb4f79c8594036955
        imagePullPolicy: IfNotPresent
        name: dns-test-server
        ports:
        - containerPort: 53
          name: dns-53
          protocol: TCP
        - containerPort: 53
          name: dns-udp-53
          protocol: UDP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/coredns
          name: coredns-config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: echo-same-node
      serviceAccountName: echo-same-node
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          name: coredns-configmap
        name: coredns-config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-04-21T17:37:18Z"
    lastUpdateTime: "2023-04-21T17:37:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-04-21T17:37:10Z"
    lastUpdateTime: "2023-04-21T17:37:18Z"
    message: ReplicaSet "echo-same-node-85bc9b6b56" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
